### ISSUE TITLE
when trying to swipe from month to month it jumps back to current month

### ISSUE THREAD

**Issue by liesislukas** [vlad-doru/react-native-calendar-datepicker#1]
from 10 tries only once got a jump from 1 month to next one

with this guesture:
![image](https://cloud.githubusercontent.com/assets/2733862/19681424/03c9da00-9ab2-11e6-988f-f4acccedcea0.png)

It just slides and jumps back, you have to slide quite heavily to actually jump to next month.

**Comment by vlad-doru** [comment]
What platform? I'll look into it ^^

**Comment by liesislukas** [comment]
i'm testing with ios now, but will need it to work well on Android too, thanks. There could be some "force" option for this

**Comment by vlad-doru** [comment]
Will take a look asap.

**Comment by vlad-doru** [comment]
Please post the iOS device and OS you were testing on, as well as the version of React Native. 

Thanks

**Comment by liesislukas** [comment]
I'm getting better at this :-) but still many times it doesn't slide:

https://www.youtube.com/watch?v=TLtrGgLab8M&feature=youtu.be

react-native: "0.34.1",
![image](https://cloud.githubusercontent.com/assets/2733862/19682255/72060dba-9ab5-11e6-8a21-44602d72335c.png)

**Comment by vlad-doru** [comment]
I set the threshold as following:

`const threshold = _.min([width / 3, 250]);`

I will allow setting a custom value for that threshold.
