### ISSUE TITLE
Showing only month and year

### ISSUE THREAD

**Issue by Akshay9882** [vlad-doru/react-native-calendar-datepicker#12]
Is it possible to modify this calendar to shown only months and year, i want to modify it to show only months and years like below view
```
<     2017           >
   Jan   Feb    Mar
   Apr   May    Jun
   Jul   Aug    Sep 
   Oct   Nov    Dec
```

**Comment by vlad-doru** [comment]
I modified it for you, you just need to upgrade to version 1.2.2 and add the property finalStage="month"

**Comment by Akshay9882** [comment]
Ok thanks
