### ISSUE TITLE
use custom moment calendar

### ISSUE THREAD

**Issue by cyclops24** [vlad-doru/react-native-calendar-datepicker#14]
Hi guys,
Is it possible to use custom moment calendar with this calendar?
For example with this plugin: https://momentjs.com/docs/#/plugins/jalaali/

**Comment by vlad-doru** [comment]
It seems like it should. If you try it out, let me know if it works or not ^^

**Comment by cyclops24** [comment]
Thanks @vlad-doru ,
Can you guide me how we can do this?
Is it need to change source code or any option available for this?

**Comment by vlad-doru** [comment]
you would need to change the source code.. you would have to add an option that you would then check and use the custom moment funcitons atferwards.
