### ISSUE TITLE
some grey matter during animation in iOS

### ISSUE THREAD

**Issue by liesislukas** [vlad-doru/react-native-calendar-datepicker#2]
# Because you use slide animation and there is no option for it, if i add shadow for entire calendar with:

``` javascript
<Calendar
        style={{
          marginTop: 24,
          marginBottom: 24,
          backgroundColor: colors.background,
          shadowColor: "#fff",
          shadowOpacity: 0.4,
          shadowRadius: 2,
          shadowOffset: {height: 0, width: 0},
          alignSelf: 'center',
        }}
...
```

**during** animations i see that shadow:

![image](https://cloud.githubusercontent.com/assets/2733862/19681876/cfe282d0-9ab3-11e6-9990-42965b1abbdd.png)

there could be an option to have different animation, like `fade` or disable animations all together

**Comment by vlad-doru** [comment]
Please give more details on the issue. The full Calendar snippet would be much appreciated.

**Comment by vlad-doru** [comment]
Will mark this as closed until further info will be provided
