### ISSUE TITLE
Adding or subtracting a year from current one.

### ISSUE THREAD

**Issue by reformer** [vlad-doru/react-native-calendar-datepicker#5]
Hi,
I'm going to customize this library. I don't want change year after changing slider. It also feel be good way for adding and subtracting a year from current.
![screen shot 2017-01-10 at 8 28 29 pm](https://cloud.githubusercontent.com/assets/10958854/21810835/65e177e0-d773-11e6-9602-7ca5b445c8a0.png)

I added two button on top of calendar bar in Calendar class.

`<View style={{flexDirection: 'row',backgroundColor:'#d8d8d8'}}>

          <Awesome name='angle-left' onPress={()=> this._previousYear()} size={30} color='#000' style={styles.iconLeft}/>

          <TouchableHighlight
              activeOpacity={this.state.stage !== YEAR_SELECTOR ? 0.8 : 1}
              underlayColor={barStyle ? barStyle.backgroundColor : 'transparent'}
              style={[styles.barView, this.props.barView]}>
            <Text style={this.props.barText}>
              {this._stageText()}
            </Text>
          </TouchableHighlight>

          <Awesome name='angle-right' onPress={()=> this._nextYear()} size={30} color='#000'  style={styles.iconLeft}/>
        </View>`

I want when i tap on next and previous button i need to change year calendar view. I tried a lot but no luck. If you have any way please let me know.

**Comment by vlad-doru** [comment]
I am having a really hard time understanding your problem. Please create a new issue with a more detailed explanation of what you would want to achieve. Also, please keep in mind that you can also patch the code and then submit a pull request.
